reference_path: data/spatial/wu_reference/wu_breast_atlas_rectangle.h5ad
cell_type_column: celltype_minor
selected_cell_types: []
excluded_cell_types:
  - Cycling T-cells
  - Cycling_Myeloid
  - Cancer Cycling
  - Cycling PVL
  - Myoepithelial
  - Luminal Progenitors
  - Mature Luminal
correct_mrna_bias: true
n_cpus: null
gene_symbol_policy: upper
min_genes_overlap: 500
